### ISSUE TITLE
Allow precompiled EVM bytecode on contract deployment

### ISSUE THREAD

**Issue by peterbroadhurst** [kaleido-io/ethconnect#18]
Most non-trivial contracts involved multiple solidity files, and cannot simply be in-lined in a YAML/JSON payload. So ethconnect should provide a way to use `solc` locally, and supply the compiled contract code (along with the simple mechanism for sending the constructor parameters, like we have for `SendTransaction`).

Today these more sophisticated contracts need to be installed by other code/tools, before sending transactions in with ethconnect.

**Comment by shiqinfeng1** [comment]
Does it support now？

**Comment by peterbroadhurst** [comment]
Hi @shiqinfeng1,

The API for submitting a compiled contract + ABI to the built-in store is described here:
https://api.kaleido.io/ethconnect.html#tag/Smart-Contract-REST-APIs/paths/~1/post

On the Kaleido platform, we've actually gone quite a bit further an added end to end contract management to manage the ABIs and contract bytecode across all the nodes in your environment:
https://www.kaleido.io/blockchain-blog/smart-contract-management-solution-how-it-works-why-you-need-it

Sorry this issue is stale. Closing it out.
