### ISSUE TITLE
Failed to read SASL handshake header: EOF

### ISSUE THREAD

**Issue by ehanoc** [kaleido-io/ethconnect#30]
# Issue
- When trying to start a bridge with kafka

# Info
- Running consortium through Kaleido
- Authentication details fetched from one of the nodes in the consortium

# Command

> ./ethconnect kafka -T [REPLIES] -t [REQUESTS] -b [BROKER] -u [USERNAME] -p [PASSWORD] -g consensys-solutions -r [RPC_URL] -d 2

# Log

> DEBU[2019-02-12T14:15:04Z] Log level set to 2                           
> INFO[2019-02-12T14:15:04Z] Starting Kafka bridge                        
> DEBU[2019-02-12T14:15:04Z] JSON/RPC connected. 
> DEBU[2019-02-12T14:15:04Z] Kafka TLS Enabled=false Insecure=false MutualAuth=false ClientCertsFile= PrivateKeyFile= CACertsFile= 
> DEBU[2019-02-12T14:15:04Z] Kafka ClientID: 42aee518-8fa4-4c28-4f40-8f20efa13d88 
> DEBU[2019-02-12T14:15:04Z] Kafka Bootstrap brokers: [kafka.eu-central-1.kaleido.io:9093] 
> DEBU[2019-02-12T14:15:04Z] [sarama] Initializing new client             
> DEBU[2019-02-12T14:15:04Z] [sarama] client/metadata fetching metadata for all topics from broker kafka.eu-central-1.kaleido.io:9093 
> DEBU[2019-02-12T14:15:04Z] [sarama] Failed to read SASL handshake header : EOF 
> kafka: client has run out of available brokers to talk to (Is your cluster reachable?)

**Comment by ehanoc** [comment]
Figured it out. Missing -e option (TLS)

**Comment by peterbroadhurst** [comment]
Glad you got this working @ehanoc 👍 
If you continue to experience any issues specific to use of ethconnect with the Kaleido SaaS platform, it's probably best to raise a ticket via support@kaleido.io
