### ISSUE TITLE
Swagger includes a POST root on the base /:address in cases it shouldn't

### ISSUE THREAD

**Issue by peterbroadhurst** [kaleido-io/ethconnect#36]
When an contract registry plugpoint is used, there is no `POST` available on `/gateways/:gateway_id/:address`, but the swagger generation still adds it:

https://github.com/kaleido-io/ethconnect/blob/b88d74cfdb0d28df3e413a1ce47abb0c2cfe68fe/internal/kldopenapi/abi2swagger.go#L107-L109

**Comment by vdamle** [comment]
Fixed
