### ISSUE TITLE
Swagger UI does not surface body parameters when subscribing to events via a Gateway API 

### ISSUE THREAD

**Issue by nickgaski** [kaleido-io/ethconnect#50]
Body parms aren't available in the console interactive swagger instance.  Expect to see `"fromBlock"` and `"stream"`.

![image](https://user-images.githubusercontent.com/16326255/74196486-5618ec00-4c2b-11ea-9403-8ac1003f312b.png)

No issue when subscribing directly from a contract instance.

**Comment by peterbroadhurst** [comment]
Resolved in #58
